### ISSUE TITLE
ConnectionRefusedError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by heathersherry** [AhmadSakor/falcon#1]
Hi,

I came across this connection error while running the main.py.

GET http://localhost:9200/dbontologyindex/doc/_search [status:N/A request:0.007s]
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

Could you please give some hints for solving this problem? Thanks a lot!

**Comment by AhmadSakor** [comment]
Hi,

Did you create an endpoint for elasticsearch, and added the elastic dump ?
The error says the connection to the endpoint is not possible
